remove unused config

diff --git a/.github/workflows/run-ansible.yml b/.github/workflows/run-ansible.yml
--- a/.github/workflows/run-ansible.yml
+++ b/.github/workflows/run-ansible.yml
@@ -99,15 +99,23 @@ jobs:
           # set pipefail so that the pipeline will fail if any command fails so we're sure tee doesn't swallow the error
           set -o pipefail
 
+          FAILED=0
+
           find ./inventory/ -type f -name "*.cfg" -print | while read -r inventory; do
             inventory="$(basename -s .cfg "$inventory")"
             IS_DEFAULT_BRANCH="${{ github.ref_name == github.event.repository.default_branch}}"
             CHECK="--check"
             if [[ "$IS_DEFAULT_BRANCH" == "true" ]]; then
               CHECK=""
-              ansible-playbook "./playbooks/$inventory.yml" --inventory "./inventory/$inventory.cfg" $CHECK
+              if ! ansible-playbook "./playbooks/$inventory.yml" --inventory "./inventory/$inventory.cfg" $CHECK; then
+                echo "ANSIBLE RUN FAILED FOR $inventory"
+                FAILED=1
+              fi
             else
-              ansible-playbook "./playbooks/$inventory.yml" --inventory "./inventory/$inventory.cfg" $CHECK 2>&1 | tee output.txt
+              if ! ansible-playbook "./playbooks/$inventory.yml" --inventory "./inventory/$inventory.cfg" $CHECK 2>&1 | tee output.txt; then
+                echo "ANSIBLE RUN FAILED FOR $inventory"
+                FAILED=1
+              fi
             fi
           done
 
@@ -115,6 +123,8 @@ jobs:
           if [[ -s output.txt ]]; then
             echo "ansible-dry-run="$(cat output.txt) >> $GITHUB_OUTPUT
           fi
+
+          exit $FAILED
 
       - uses: mshick/add-pr-comment@v2
         if: (!cancelled())
